package com.keepit.model

object Words {
  val nouns = Array[String]("time", "year", "people", "thing", "life", "child", "world", "school", "state", "family",
    "student", "group", "country", "problem", "hand", "part", "place", "case", "week", "company", "system", "program",
    "question", "work", "number", "night", "point", "home", "water", "room", "mother", "area", "money", "story", "fact",
    "month", "right", "study", "book", "word", "business", "issue", "side", "kind", "head", "house", "service", "friend",
    "father", "power", "hour", "game", "line", "member", "city", "name", "team", "minute", "idea", "body", "back",
    "parent","face", "others", "level", "office", "door", "health", "person", "history", "party", "result", "change",
    "morning", "reason", "research", "girl", "food", "moment", "teacher", "force", "foot", "policy", "process", "music",
    "market", "sense", "nation", "plan", "college", "interest", "death", "effect", "class", "control", "care", "field",
    "role", "effort", "rate", "heart", "drug", "show", "leader", "light", "voice", "wife", "police", "mind", "price",
    "report", "decision", "view", "town", "road", "value", "building", "action", "model", "season", "society", "director",
    "position", "player", "record", "paper", "space", "ground", "form", "event", "official", "matter", "center", "couple",
    "site", "project", "activity", "star", "table", "need", "court", "cost", "industry", "figure", "street", "image",
    "phone", "data", "picture", "practice", "piece", "land", "product", "doctor", "wall", "patient", "worker", "news",
    "test", "movie", "north", "love", "support", "step", "baby", "computer", "type", "film", "tree", "source", "hair",
    "look", "century", "evidence", "window", "culture", "chance", "brother", "energy", "period", "course", "summer",
    "plant", "term", "letter", "choice", "rule", "daughter", "south", "husband", "congress", "floor", "campaign",
    "material", "call", "economy", "hospital", "risk", "fire", "future", "defense", "security", "bank", "west",
    "sport", "board", "subject", "officer", "rest", "behavior", "goal", "second", "order", "author", "blood", "agency",
    "nature", "color", "store", "sound", "movement", "page", "race", "concern", "series", "language", "response",
    "animal", "factor", "decade", "article", "east", "artist", "scene", "stock", "career", "approach", "size", "fund",
    "media", "sign", "thought", "list", "quality", "pressure", "answer", "resource", "meeting", "disease", "success",
    "amount", "ability", "staff", "growth", "loss", "degree", "attack", "region", "training", "trade", "deal", "election",
    "feeling", "standard", "bill", "message", "analysis", "benefit", "lawyer", "section", "glass", "skill", "sister",
    "crime", "stage", "design", "sort", "station", "strategy", "truth", "song", "example", "public", "rock", "note",
    "manager", "help", "network", "science", "memory", "card", "seat", "cell", "trial", "expert", "spring", "firm",
    "democrat", "radio", "ball", "talk", "theory", "impact", "charge", "weapon", "employee", "peace", "base", "pain",
    "play", "measure", "chair", "fish", "camera", "politics", "weight", "trip", "evening", "unit", "style", "adult",
    "range", "past", "edge", "writer", "trouble", "fear", "shoulder", "dream", "property", "stuff", "detail", "method",
    "magazine", "hotel", "soldier", "cause", "heat", "fall", "marriage", "surface", "purpose", "pattern", "skin", "agent",
    "owner", "machine", "cancer", "item", "reality", "coach", "yard", "violence", "finger", "garden", "task", "partner",
    "kitchen", "consumer", "shot", "budget", "painting", "capital", "mouth", "victim", "threat", "attorney", "score",
    "account", "break", "audience", "dinner", "vote", "debate", "citizen", "majority", "wind", "mission", "customer",
    "speech", "option", "forest", "video", "senate", "reform", "access", "judge", "relation", "bird", "opinion", "credit",
    "corner", "version", "safety", "troop", "income", "species", "track", "hope", "freedom", "plane", "object", "attitude",
    "labor", "concept", "client", "variety", "turn", "press", "conflict", "spirit", "argument", "camp", "brain", "feature",
    "weekend", "battle", "date", "crisis", "hole", "element", "vision", "status", "ship", "solution", "stone", "scale",
    "driver", "attempt", "park", "spot", "lack", "boat", "distance", "wood", "truck", "return", "mountain", "survey",
    "winter", "village", "sales", "screen", "resident", "gold", "club", "farm", "increase", "middle", "presence",
    "district", "shape", "reader", "contract", "crowd", "strength", "band", "horse", "target", "prison", "guard",
    "demand", "reporter", "text", "share", "tool", "vehicle", "flight", "facility", "pound", "basis", "guest", "sample",
    "block", "while", "identity", "title", "lesson", "faith", "river", "living", "path", "shop", "folk", "border", "claim",
    "critic", "aspect", "failure", "comment", "affair", "chairman", "baseball", "belief", "gift", "review",
    "editor", "coffee", "document", "speed", "youth", "wave", "move", "quarter", "reaction", "suit", "shoe", "grade",
    "context", "mistake", "focus", "smile", "location", "clothes", "neighbor", "drive", "function", "bone", "average",
    "wine", "voter", "mean", "learning", "hell", "category", "victory", "visit", "internet", "medicine", "tour", "photo",
    "finding", "contact", "justice", "pair", "exercise", "knee", "flower", "tape", "supply", "will", "actor", "birth",
    "search", "circle", "device", "progress", "front", "bottom", "island", "exchange", "studio", "lady", "neck", "damage",
    "plastic", "plate", "writing", "start", "football", "chicken", "army", "abuse", "theater", "session", "danger",
    "rain", "desire", "injury", "respect", "fuel", "leaf", "fight", "pool", "lead", "engine", "salt", "metal", "ticket",
    "software", "reading", "lunch", "farmer", "sugar", "planet", "enemy", "athlete", "soul", "panel", "meaning",
    "weather", "pocket", "surprise", "poll", "proposal", "half", "breath", "sight", "cover", "balance", "minority",
    "works", "teaching", "advice", "trail", "novel", "code", "jury", "breast", "human", "theme", "storm", "union",
    "desk", "thanks", "fruit", "shadow", "analyst", "dance", "limit", "being", "ring", "revenue", "county", "package",
    "bridge", "train", "e-mail", "thinking", "trend", "visitor", "loan", "investor", "profit", "crew", "accident", "male",
    "meal", "hearing", "traffic", "muscle", "notion", "earth", "chest", "cash", "museum", "beauty", "stress", "content",
    "root", "nose", "bottle", "setting", "dress", "file", "outcome", "duty", "sheet", "extent", "contrast", "zone",
    "airport", "chief", "shirt", "pilot", "capacity", "estate", "guide", "snow", "meat", "soil", "surgery", "golf",
    "chain", "address", "branch", "governor", "relief", "user", "manner", "silence", "rating", "motion", "gender", "bowl",
    "frame", "host", "hall", "ocean", "producer", "regime", "division", "appeal", "mirror", "tooth", "length", "topic",
    "variable", "bedroom", "secret", "debt", "tank", "nurse", "coverage", "bond", "pleasure", "master", "check", "stand",
    "wing", "struggle", "judgment", "beer", "english", "tear", "doubt", "minister", "hero", "cloud", "winner", "volume",
    "travel", "seed", "fashion", "pepper", "copy", "welfare", "dish", "beach", "opening", "route", "league", "core",
    "rise", "holiday", "abortion", "witness", "sector", "black", "incident", "flow", "faculty", "waste", "mass", "bomb",
    "tone", "engineer", "wheel", "female", "promise", "cable", "aids", "cream", "gate", "hill", "noise", "grass",
    "fishing", "drink", "talent", "taste", "milk", "sentence", "height", "sleep", "ride", "campus", "column", "signal",
    "honor", "offer", "asset", "prayer", "scholar", "warning", "climate", "cheese", "payment", "priority", "bread",
    "creation", "graduate", "request", "emotion", "universe", "mark", "green", "airline", "library", "agenda", "factory",
    "roof", "expense", "diet", "funding", "therapy", "schedule", "housing", "post", "dark", "steel", "chip", "self",
    "bike", "layer", "planning", "wedding", "portion", "opponent", "link", "lake", "tension", "display", "alcohol",
    "saving", "gain", "desert", "error", "release", "walk", "sand", "print", "passage", "album", "cycle", "whole",
    "exposure", "stream", "sale", "trust", "tale", "knife", "phase", "present", "joke", "coat", "symptom", "potato",
    "pass", "good", "occasion", "dust", "jacket", "shift", "touch", "iron", "passion", "gene", "sauce", "advance",
    "employer", "shock", "illness", "habit", "juice", "disaster", "parking", "prospect", "boss", "mystery", "poverty",
    "entry", "spending", "king", "symbol", "maker", "mood", "emphasis", "boot", "bean", "creature", "total", "anger",
    "peak", "disorder", "missile", "wire", "round", "twin", "command", "stop", "luck", "clinic", "veteran", "tourist",
    "tomato", "butter", "deficit", "bathroom", "ally", "journey", "mixture", "tower", "smoke", "prisoner", "peer",
    "designer", "educator", "relative", "belt", "teaspoon", "birthday", "coast", "silver", "teenager", "flag", "recovery",
    "watch", "corn", "moon", "throat", "salary", "observer", "crop", "strike", "anxiety", "viewer", "mayor", "estimate",
    "buck", "poem", "testing", "stomach", "mail", "recipe", "concert", "channel", "tube", "drawing", "protein", "absence",
    "roll", "jail", "pace", "speaker", "essay", "cake", "origin", "approval", "mine", "drop", "count", "depth", "wealth",
    "shell", "pack", "onion", "deputy", "brand", "award", "criteria", "dealer", "utility", "highway", "routine", "wage",
    "phrase", "stake", "fiber", "activist", "refugee", "gear", "barrier", "gang", "chemical", "label", "teen",
    "index", "vacation", "advocate", "draft", "heaven", "drama", "wonder", "clock", "ceiling", "button", "bell", "rank",
    "darkness", "clothing", "fence", "portrait", "paint", "survival", "lawsuit", "bunch", "beat", "burden", "chamber",
    "string", "ceremony", "cheek", "profile", "penalty", "match", "resort", "bear", "tissue", "pant", "stranger",
    "cabinet", "apple", "virus", "dispute", "fortune", "shopping", "cousin", "white", "port", "adviser", "slave",
    "terror", "elite", "dirt", "rice", "bullet", "chart", "decline", "stick", "champion", "scenario", "strip",
    "fiction", "lifetime", "senator", "hunting", "salad", "boundary", "journal", "bench", "lover", "general", "deck",
    "pole", "mode", "dialogue", "founder", "pride", "aircraft", "delivery", "platform", "finance", "worth", "singer",
    "shooting", "offense", "counter", "smell", "transfer", "protest", "crash", "craft", "treaty", "insight",
    "episode", "fault", "assault", "stair", "proof", "tongue", "license", "hold", "shelter", "entrance",
    "favorite", "tragedy", "mask", "deer", "emission", "fate", "earnings", "oven", "segment",
    "poet", "comfort", "honey", "musician", "load", "vessel", "storage", "leather", "tribe", "shelf",
    "lawn", "buyer", "dining", "wisdom", "council", "instance", "garlic", "poetry", "fantasy", "plot",
    "gesture", "chapter", "fellow", "divorce", "pipe", "math", "shade", "tail", "angle", "palm",
    "custom", "soup", "pile", "carbon", "scheme", "crack", "tobacco", "survivor", "galaxy", "meter",
    "arrest", "fighter", "hunter", "aide", "infant", "porch", "tendency", "uniform", "mall", "scandal",
    "heel", "privacy", "fabric", "contest", "rifle", "trick", "tent", "myth", "standing", "tennis",
    "nerve", "barrel", "bombing", "ratio", "menu", "purchase", "humor", "glove", "suspect",
    "provider", "delay", "stroke", "scope", "handful", "horizon", "taxpayer", "workshop", "auto", "cotton",
    "motor", "flavor", "sequence", "blade", "cabin", "edition", "valley", "pitch", "pine", "complex",
    "chef", "german", "boom", "heritage", "lemon", "legacy", "battery", "arrival", "flame", "cluster",
    "wound", "shower", "flesh", "garage", "operator", "comedy", "mortgage", "sanction", "habitat", "grain",
    "province", "ethics", "actress", "summit", "acid", "odds", "medium", "grant", "shore", "lung",
    "basket", "fighting", "powder", "ghost", "cookie", "carrier", "cooking", "swing", "orange", "miracle",
    "rhythm", "charity", "script", "tactic", "headline", "venture", "invasion", "military", "piano",
    "grocery", "blanket", "margin", "mouse", "rope", "brick", "patch", "horror", "painter", "sake",
    "gaze", "courage", "clue", "slice", "coal", "criminal", "formula", "uncle", "square", "captain",
    "gallery", "soccer", "tunnel", "fitness", "grave", "virtue", "makeup", "inquiry", "rose", "rail",
    "couch", "alliance", "mess", "legend", "norm", "remark", "reward", "organ", "laughter", "receiver",
    "ritual", "insect", "salmon", "favor", "trading", "combat", "stem", "surgeon", "physics",
    "counsel", "brush", "jeans", "pill", "compound", "flour", "slope", "serving", "bishop", "drinking",
    "collapse", "pump", "candy", "evil", "final", "medal", "export", "midnight", "curve", "logic",
    "essence", "closet", "interior", "corridor", "pitcher", "snake", "cross", "weakness", "cold", "t-shirt",
    "humanity", "beef", "stretch", "elbow", "airplane", "duck", "dose", "lecture",
    "suburb", "sandwich", "trunk", "rumor", "cloth", "lens", "reach", "fraud", "nail", "array",
    "hallway", "cave", "monster", "obstacle", "herb", "crystal", "wish", "motive", "flood", "notice",
    "arena", "laugh", "basement", "warrior", "bacteria", "temple", "wrist", "curtain", "monitor", "pond",
    "domain", "guilt", "cattle", "walking", "playoff", "skirt", "database", "limb", "ideology", "harm",
    "railroad", "horn", "strain", "guitar", "dancer", "grace", "colony", "adoption", "slide", "civilian",
    "towel", "particle", "glance", "prize", "landing", "conduct", "blue", "alarm", "festival", "grip",
    "freshman", "sweat", "ballot", "rhetoric", "vitamin", "mandate", "pause", "excuse", "chaos",
    "canvas", "lobby", "format", "trait", "currency", "turkey", "reserve", "beam", "doctrine", "thumb",
    "unity", "rush", "fork", "disk", "lock", "finish", "shame", "sidewalk", "olympics", "rebel",
    "spouse", "fluid", "pension", "sodium", "blow", "forehead", "hook", "traveler", "exit", "pickup",
    "needle", "belly", "shuttle", "timing", "ankle", "rider", "doll", "noon", "exhibit", "liberty",
    "poster", "theology", "oxygen", "magic", "donor", "jazz", "opera", "bite",
    "wildlife", "giant", "primary", "equity", "doorway", "elevator", "guidance", "statue", "pursuit", "repair",
    "clerk", "israeli", "envelope", "fist", "bath", "rescue", "sunlight", "feedback", "spectrum", "laser",
    "starting", "tune", "eating", "hint", "parade", "realm", "pizza", "bias", "metaphor", "candle",
    "handle", "worry", "entity", "feel", "lamp", "garbage", "servant", "addition", "inside", "chin",
    "racism", "starter", "banking", "gravity", "intent", "assembly", "silk", "hostage", "kiss",
    "alien", "equation", "angel", "switch", "offering", "rage", "toilet", "wake", "dawn",
    "tide", "romance", "hardware", "pillow", "cook", "spread", "circuit", "sink", "ruling", "shortage",
    "trap", "fool", "deadline", "ranch", "diamond", "import", "cart", "elder", "quantity", "trailer",
    "mate", "genius", "monument", "quest", "accuracy", "juror", "broker", "treasure", "loyalty", "gasoline",
    "output", "nominee", "diabetes", "grief", "rocket", "inmate", "dynamics", "senior", "dignity", "carpet",
    "bubble", "buddy", "barn", "sword", "flash", "glory", "drum", "queen", "dilemma", "input",
    "merchant", "stadium", "defeat", "nest", "lane", "ancestor", "steam", "accent", "escape", "cage",
    "shrimp", "homeland", "rack", "costume", "wolf", "statute", "cartoon", "seal", "aunt", "vaccine",
    "bonus", "orbit", "patience", "voting", "patrol", "rent", "jewelry", "trace", "wagon", "bush",
    "clip", "thigh", "bull", "drawer", "sheep", "runner", "empire", "exam", "biology", "catch",
    "casualty", "republic", "whale", "instinct", "teammate", "aluminum", "ministry", "verdict", "skull", "ease",
    "loop", "puzzle", "mushroom", "subsidy", "mechanic", "pork", "dessert", "sympathy", "sock", "jump",
    "syndrome", "bureau", "ambition", "breeze", "booth", "helmet", "waist", "lion", "panic", "cast",
    "cliff", "cord", "illusion", "casino", "tumor", "pulse", "donation", "diary", "sibling",
    "irony", "spoon", "midst", "alley", "soap", "rival", "hockey", "supplier", "momentum", "purse",
    "liquid", "icon", "elephant", "bicycle", "fever", "filter", "rabbit", "coin", "organism", "stay",
    "minimum", "backyard", "charter", "stove", "consent", "reminder", "dough", "outfit", "workout", "patent",
    "quote", "trash", "hormone", "texture", "pencil", "frontier", "spray", "custody", "banker", "beast",
    "notebook", "shark", "mill", "swimming", "fleet", "catalog", "outsider", "stance", "debut", "ideal",
    "trainer", "scent", "stack", "eyebrow", "sack", "tray", "pioneer", "textbook", "wheat", "kingdom",
    "aisle", "protocol", "terrain", "pasta", "genre", "merit", "planner", "chunk", "discount", "ladder",
    "jungle", "retailer", "coup", "density", "stimulus", "robot", "feather", "sphere", "major", "validity",
    "collar", "weed", "streak", "builder", "glimpse", "premise", "artifact", "monkey", "mentor", "listener",
    "sleeve", "debris", "liberal", "parish", "slavery", "cure", "mineral", "hunger", "equality",
    "fame", "carrot", "toll", "squad", "sponsor", "grin", "chill", "refuge", "rally", "outlet",
    "vendor", "peanut", "auction", "steak", "triumph", "interval", "butt", "bulk", "patron", "liver",
    "harmony", "instant", "goat", "blessing", "banana", "running", "palace", "peasant", "lawmaker", "cruise",
    "plain", "calendar", "widow", "deposit", "beard", "brake", "impulse", "predator", "forum", "dancing",
    "removal", "autonomy", "thread", "landmark", "offender", "fraction", "tourism", "suite", "straw", "globe",
    "blast", "denial", "rental", "fragment", "warmth", "headache", "yield", "mention", "mansion", "regard",
    "grape", "cottage", "driveway", "charm", "clay", "balloon", "fare", "homework", "disc", "sofa",
    "radar", "leave", "permit", "sweater", "retreat", "molecule", "premium", "fatigue", "marker", "bucket",
    "marble", "twist", "defender", "arrow", "trauma", "ribbon", "meantime", "harvest", "slot", "riot",
    "nutrient", "ridge", "lighting", "transit", "seminar", "shorts", "bride", "hazard", "tile", "launch",
    "delight", "timber", "plea", "bulb", "devil", "bolt", "cargo", "spine", "seller", "dock",
    "diplomat", "summary", "epidemic", "bronze", "praise", "vacuum", "sensor", "laundry", "manual", "pistol", "apology")

  val verbs = Array[String]("have", "would", "make", "know", "will", "think", "take", "come", "could", "want",
    "look", "find", "give", "tell", "work", "should", "call", "need", "feel", "become",
    "leave", "mean", "keep", "begin", "seem", "help", "talk", "turn", "start", "might",
    "show", "hear", "play", "move", "like", "live", "believe", "hold", "bring", "happen",
    "must", "write", "provide", "stand", "lose", "meet", "include", "continue", "learn", "change",
    "lead", "watch", "follow", "stop", "create", "speak", "read", "allow", "spend", "grow",
    "open", "walk", "offer", "remember", "love", "consider", "appear", "wait", "serve", "send",
    "expect", "build", "stay", "fall", "reach", "remain", "suggest", "raise", "pass",
    "sell", "require", "report", "decide", "pull", "return", "explain", "hope", "develop", "carry",
    "drive", "break", "thank", "receive", "join", "agree", "pick", "wear", "support", "base",
    "produce", "teach", "face", "cover", "describe", "catch", "draw", "choose", "cause", "point",
    "listen", "realize", "place", "close", "involve", "increase", "seek", "deal", "fight", "throw",
    "fill", "focus", "drop", "plan", "push", "reduce", "note", "enter", "share", "rise",
    "shoot", "save", "protect", "occur", "accept", "identify", "prepare", "argue", "indicate", "wonder",
    "fail", "arrive", "name", "present", "answer", "compare", "miss", "state", "discuss", "force",
    "check", "laugh", "guess", "study", "prove", "hang", "design", "forget", "claim", "remove",
    "sound", "enjoy", "form", "visit", "care", "avoid", "imagine", "finish", "respond", "maintain",
    "reveal", "contain", "head", "control", "apply", "shake", "manage", "perform", "discover", "treat",
    "affect", "worry", "mention", "improve", "sign", "reflect", "sing", "exist", "address", "test",
    "step", "beat", "tend", "notice", "wish", "smile", "figure", "relate", "travel", "prevent",
    "born", "admit", "assume", "suffer", "publish", "cost", "release", "recall", "stare", "hurt",
    "strike", "achieve", "refer", "conduct", "announce", "examine", "touch", "attend", "vote", "sleep",
    "replace", "complete", "stick", "define", "drink", "handle", "refuse", "roll", "gain", "hide",
    "express", "ride", "deliver", "observe", "emerge", "earn", "operate", "settle", "feed", "collect",
    "promote", "count", "marry", "order", "survive", "lift", "jump", "gather", "limit", "result",
    "insist", "approach", "spread", "ignore", "measure", "engage", "cross", "threaten", "commit", "deny",
    "blow", "destroy", "cook", "charge", "burn", "view", "dress", "promise", "extend", "combine",
    "demand", "remind", "fire", "depend", "grab", "hire", "train", "lean", "hate", "press",
    "intend", "attack", "shut", "welcome", "paint", "direct", "climb", "expand", "explore", "obtain",
    "surround", "invite", "repeat", "predict", "bear", "adopt", "attempt", "connect", "belong", "organize",
    "record", "fear", "struggle", "conclude", "last", "shift", "mark", "locate", "generate", "propose",
    "capture", "prefer", "search", "feature", "link", "select", "declare", "launch", "defend", "matter",
    "judge", "ought", "ensure", "wake", "warn", "steal", "pursue", "slip", "blame", "estimate",
    "kick", "solve", "trust", "score", "afford", "confirm", "rely", "complain", "issue", "back",
    "range", "attract", "file", "clear", "pour", "stir", "clean", "grant", "account", "stretch",
    "rest", "separate", "cite", "divide", "oppose", "question", "rush", "employ", "dance", "match",
    "lack", "decline", "invest", "expose", "succeed", "accuse", "hand", "land", "reject", "escape",
    "cast", "convince", "assess", "lower", "approve", "acquire", "compete", "mind", "list", "regard",
    "knock", "review", "wrap", "display", "suspect", "permit", "scream", "drag", "recover", "arrest",
    "wash", "purchase", "shout", "suppose", "perceive", "slow", "slide", "inform", "abandon", "bother",
    "consist", "enable", "bend", "shall", "rule", "preserve", "arrange", "reply", "lock", "deserve",
    "tear", "pose", "benefit", "resolve", "contact", "quote", "urge", "breathe", "elect", "pack",
    "inspire", "adjust", "retire", "kiss", "dominate", "transfer", "analyze", "attach", "coach", "exercise",
    "enhance", "impose", "evaluate", "trade", "monitor", "vary", "ring", "race", "smell", "light",
    "toss", "bury", "pray", "block", "confront", "glance", "shape", "whisper", "swing", "plant",
    "resist", "embrace", "supply", "assist", "line", "date", "secure", "smoke", "bind", "favor",
    "weigh", "install", "quit", "comment", "restore", "advise", "assure", "arise", "schedule", "dream",
    "snap", "switch", "graduate", "assign", "wave", "yell", "sweep", "spin", "house", "yield",
    "wind", "found", "react", "taste", "disagree", "advance", "proceed", "track", "overcome", "occupy",
    "wipe", "honor", "retain", "process", "detect", "balance", "flow", "market", "pause", "withdraw",
    "testify", "imply", "dismiss", "bake", "freeze", "sink", "respect", "evolve", "justify", "possess",
    "double", "swim", "tire", "free", "relax", "practice", "fade", "alter", "spot", "squeeze",
    "target", "convert", "load", "appeal", "pretend", "split", "stress", "adapt", "flee",
    "doubt", "guide", "witness", "sustain", "mount", "differ", "store", "damage", "satisfy", "consume",
    "fund", "trace", "educate", "waste", "qualify", "derive", "impress", "resemble", "surprise", "rate",
    "explode", "prompt", "request", "absorb", "overlook", "float", "undergo", "assert", "print", "bite",
    "risk", "suit", "register", "appoint", "sense", "wander", "submit", "shrug", "cope", "host",
    "depict", "collapse", "borrow", "brush", "devote", "crack", "ease", "seize", "function", "correct",
    "portray", "persuade", "admire", "exceed", "crash", "exhibit", "chase", "document", "recruit", "swear",
    "defeat", "sigh", "dare", "cool", "decrease", "compose", "peer", "rank", "regulate", "shine",
    "upset", "resign", "invent", "concern", "hunt", "echo", "rent", "delay", "shop", "finance",
    "sponsor", "slam", "melt", "entitle", "park", "exclude", "greet", "march", "pitch",
    "excuse", "fold", "reverse", "flash", "confuse", "plead", "initiate", "swallow", "motivate", "render",
    "trap", "restrict", "enforce", "lend", "contend", "assemble", "burst", "speed", "protest", "label",
    "consult", "forgive", "warm", "project", "drift", "drain", "hurry", "suck", "leap", "dump",
    "execute", "average", "tune", "endure", "behave", "guard", "await", "trigger", "spill", "convict",
    "modify", "award", "boost", "survey", "research", "stuff", "govern", "praise", "injure", "abuse",
    "scatter", "convey", "twist", "relieve", "suspend", "desire", "resume", "rebuild", "bounce", "click",
    "signal", "dedicate", "carve", "ship", "scare", "rescue", "diagnose", "crawl", "frame", "punish",
    "endorse", "program", "picture", "advocate", "strip", "cancel", "blend", "slice", "peel", "hesitate",
    "flip", "debate", "vanish", "trail", "confess", "enroll", "diminish", "value", "minimize", "chop",
    "isolate", "pump", "repair", "prohibit", "command", "stumble", "descend", "hook", "seal", "scan",
    "reserve", "spring", "oversee", "stem", "credit", "shock", "please", "slap", "donate", "tackle",
    "heat", "tuck", "post", "sail", "condemn", "unite", "equip", "exchange", "grin", "bless",
    "rock", "root", "conceive", "grasp", "position", "calm", "haul", "concede", "ruin", "divorce",
    "star", "draft", "instruct", "edit", "whip", "boil", "seat", "utilize", "dissolve", "object",
    "spell", "insert", "crush", "tolerate", "harm", "scramble", "decorate", "sort", "interact", "punch",
    "persist", "shed", "foster", "cheat", "access", "heal", "exploit", "shove", "comprise", "counter",
    "disclose", "outline", "gaze", "uncover", "reward", "compel", "proclaim", "hike", "cease", "inherit",
    "shrink", "model", "envision", "weaken", "deploy", "distract", "invade", "classify", "wound", "skip",
    "flood", "tighten", "boast", "unfold", "joke", "deem", "sneak", "disturb", "pile", "spare",
    "cure", "regret", "cling", "blink", "plunge", "color", "rain", "steer", "cheer", "thrive",
    "chew", "comply", "scratch", "strain", "sprinkle", "forbid", "poke", "trouble", "soar", "enact",
    "round", "remark", "exhaust", "circle", "prevail", "screw", "battle", "drill", "pound", "frown",
    "regain", "update", "spark", "preach", "bomb", "provoke", "fish", "mutter", "depart", "soak",
    "transmit", "screen", "specify", "crowd", "swell", "soften", "weave", "copy", "trim", "drown",
    "spit", "harvest", "kneel", "dictate")

  val adverbs = Array[String]("just", "then", "more", "also", "here", "well", "only", "very", "even", "back",
    "there", "down", "still", "when", "never", "really", "most", "about", "over", "again",
    "where", "right", "always", "today", "long", "away", "often", "ever", "however", "almost",
    "later", "much", "once", "least", "together", "around", "already", "enough", "both", "maybe",
    "actually", "probably", "home", "course", "perhaps", "little", "else", "finally", "less", "better",
    "early", "either", "quite", "simply", "nearly", "soon", "quickly", "recently", "before", "usually",
    "thus", "exactly", "hard", "pretty", "forward", "clearly", "indeed", "rather", "that", "tonight",
    "close", "suddenly", "best", "instead", "ahead", "fast", "alone", "directly", "please", "along",
    "easily", "through", "slowly", "inside", "highly", "mostly", "tomorrow", "anyway", "slightly", "twice",
    "kind", "below", "fully", "above", "straight", "okay", "somehow", "under", "largely", "anymore",
    "possibly", "deep", "truly", "outside", "hardly", "neither", "late", "part", "forth", "entirely",
    "aside", "anywhere", "somewhat", "totally", "apart", "barely", "merely", "closely", "first", "behind",
    "forever", "deeply", "fairly", "widely", "rarely", "moreover", "sure", "whenever", "heavily", "equally",
    "strongly", "surely", "rapidly", "quietly", "general", "normally", "roughly", "like", "though", "gently",
    "likely", "newly", "mainly", "partly", "shortly", "properly", "easy", "nowhere", "since", "briefly",
    "besides", "publicly", "badly", "across", "high", "abroad", "lightly", "tight", "greatly", "online",
    "daily", "frankly", "last", "past", "hence", "wherever", "nearby", "short", "commonly", "firmly",
    "loud", "wrong", "thereby", "overall", "sharply", "readily", "annually", "lately", "softly",
    "tightly", "safely", "near", "actively", "mentally", "upstairs", "alike", "someday", "openly", "likewise",
    "strictly", "legally", "socially", "halfway", "this", "solely", "formerly", "downtown", "happily", "freely",
    "steadily", "beyond", "within", "severely", "terribly", "sudden", "seldom", "honestly", "public", "sometime")

  val adjectives = Array[String]("other", "good", "high", "great", "small", "large", "national", "young", "black", "long",
    "little", "white", "real", "best", "right", "social", "only", "public", "sure", "early",
    "able", "human", "local", "late", "hard", "major", "better", "economic", "strong", "possible",
    "whole", "free", "military", "true", "federal", "full", "special", "easy", "clear", "recent",
    "certain", "personal", "open", "likely", "short", "single", "medical", "current", "wrong", "private",
    "past", "foreign", "fine", "common", "poor", "natural", "similar", "dead", "central", "happy",
    "serious", "ready", "simple", "left", "physical", "general", "blue", "dark", "various", "entire",
    "close", "legal", "cold", "final", "main", "green", "nice", "huge", "popular", "cultural",
    "wide", "deep", "specific", "middle", "heavy", "tough", "total", "modern", "positive", "civil",
    "safe", "rich", "western", "senior", "southern", "fresh", "global", "critical", "original", "basic",
    "powerful", "perfect", "involved", "nuclear", "very", "sorry", "normal",
    "front", "supposed", "soviet", "future", "willing", "previous", "wild", "average", "quick",
    "light", "bright", "tiny", "present", "warm", "annual", "regular", "soft", "female",
    "afraid", "native", "broad", "growing", "quiet", "aware", "complete", "active", "chief", "cool",
    "moral", "united", "academic", "healthy", "negative", "direct", "daily", "fair", "famous", "familiar",
    "eastern", "primary", "clean", "tall", "male", "alive", "extra", "domestic", "northern", "sweet",
    "strange", "urban", "mental", "favorite", "greatest", "complex", "married", "alone", "supreme", "thin",
    "empty", "regional", "yellow", "prime", "like", "obvious", "angry", "thick",
    "unique", "internal", "ethnic", "actual", "sick", "slow", "brown", "standard", "english",
    "funny", "correct", "crazy", "just", "ancient", "golden", "used", "equal", "official",
    "typical", "smart", "rare", "separate", "mean", "busy", "cheap", "gray", "overall", "initial",
    "terrible", "multiple", "criminal", "careful", "upper", "tired", "vast", "limited", "proud", "enormous",
    "liberal", "massive", "rural", "narrow", "solid", "useful", "secret", "unusual", "sharp", "creative",
    "outside", "proper", "live", "guilty", "living", "weak", "illegal", "israeli", "musical", "dramatic",
    "lucky", "unable", "brief", "existing", "visual", "violent", "silent", "later", "mass", "leading",
    "double", "formal", "joint", "opposite", "grand", "online", "glad", "ordinary", "numerous",
    "amazing", "intense", "visible", "severe", "still", "digital", "usual", "holy", "constant", "capable",
    "nervous", "crucial", "pure", "fellow", "smooth", "nearby", "inner", "junior", "straight", "pretty",
    "pink", "historic", "apparent", "wooden", "false", "extreme", "latin", "honest", "giant", "fast",
    "flat", "armed", "clinical", "ultimate", "valuable", "minor", "classic", "rough",
    "pregnant", "distant", "super", "bottom", "lost", "unlikely", "broken", "electric",
    "literary", "stupid", "blind", "genetic", "chemical", "accurate", "olympic", "tight", "solar", "square",
    "friendly", "innocent", "remote", "mutual", "advanced", "diverse", "relevant", "ideal", "working", "unknown",
    "loose", "external", "sudden", "dirty", "stable", "elderly", "steady", "vital", "mere", "exciting",
    "radical", "pale", "round", "scared", "ongoing", "athletic", "slight", "closer", "wealthy",
    "given", "rapid", "painful", "helpful", "organic", "proposed", "asleep", "loud", "modest", "curious",
    "downtown", "eager", "detailed", "romantic", "orange", "relative", "absolute", "dominant", "hungry", "naked",
    "civilian", "weekly", "wise", "gifted", "firm", "running", "distinct", "artistic", "ugly", "worried",
    "moderate", "frequent", "awful", "lovely", "everyday", "adequate", "concrete", "changing", "colonial", "dear",
    "sacred", "exact", "okay", "homeless", "gentle", "related", "magic", "superior", "excited", "bitter",
    "bare", "subtle", "pleased", "ethical", "evident", "harsh", "suburban", "retail", "patient", "missing",
    "reliable", "roman", "deadly", "monthly", "unlike", "longtime", "plain", "strict",
    "written", "maximum", "medium", "outdoor", "random", "minimum", "fiscal", "welcome", "chronic", "peaceful",
    "retired", "grateful", "virtual", "closed", "weird", "outer", "drunk", "driving", "endless", "profound",
    "genuine", "horrible", "pleasant", "frozen", "delicate", "mild", "precise", "anxious", "handsome", "evil",
    "teenage", "decent", "oral", "generous", "purple", "bold", "judicial", "elegant", "interior", "casual",
    "civic", "steep", "dynamic", "scary", "precious", "content", "hidden", "tender", "lonely", "abstract",
    "silly", "shared", "rear", "coastal", "burning", "verbal", "tribal", "divine",
    "talented", "stiff", "extended", "toxic", "alleged", "parental", "faint", "shallow", "improved", "bloody",
    "near", "symbolic", "hostile", "combined", "mixed", "tropical", "cuban", "sheer", "prior", "immune",
    "exotic", "secure", "secular", "intimate", "neutral", "flexible", "terrific", "tragic", "sexy", "costly",
    "rolling", "expected", "royal", "minimal", "fixed", "upset", "cute", "passing", "known", "dried",
    "disabled", "gross", "damn", "vertical", "instant", "required", "colorful", "nasty", "emerging", "fierce",
    "rational", "vocal", "unfair", "risky", "closest", "informal", "sole", "partial", "added", "logical",
    "blank", "dying", "faster", "striking", "isolated", "eligible", "intact", "awake", "dumb", "neat",
    "mobile", "brutal", "valid", "unhappy", "coming", "calm", "fragile", "crowded", "level", "liquid",
    "suitable", "cruel", "loyal", "rubber", "veteran", "blond", "explicit", "magnetic", "brave", "dense",
    "sunny", "troubled", "balanced", "flying", "skilled", "managing", "marine", "boring", "fatal", "inherent",
    "selected", "naval")
}
