#!/bin/bash

# This is only to be run on instances that are running ansible against themselves

export DEBIAN_FRONTEND=noninteractive
apt-get -yq install software-properties-common python-dev

# Compile & install from source - 1.9.4 was removed from the PPA when 2.0 was released
curl -o ansible-1.9.4.tar.gz https://pypi.python.org/packages/source/a/ansible/ansible-1.9.4.tar.gz
tar xvzf ansible-1.9.4.tar.gz
cd ansible-1.9.4 && make all && make install
cd .. && rm -rf ansible-1.9.4*
ansible-playbook -i 'localhost,' --connection=local ec2-local.yml
