---
java_version: 7
java_subversion: 80
logentries_account_key: ab262b73-aff4-4fd9-b83c-8ff7b510f7f9
logentries_logs:
  - name: "{{ service }}.out"
    path: /home/fortytwo/run/{{ service }}/log/{{ service }}.out
  - name: app.log
    path: /home/fortytwo/run/{{ service }}/log/app.log
ulimit_config:
  - domain: fortytwo
    type: soft
    item: nofile
    value: 8192
  - domain: fortytwo
    type: hard
    item: nofile
    value: 8192
instance_type_key: "{{ ec2_instance_type | regex_replace('\\W', '_') }}"
