---
java_version: 7
ulimit_config:
  - domain: fortytwo
    type: soft
    item: nofile
    value: 8192
  - domain: fortytwo
    type: hard
    item: nofile
    value: 8192
instance_type_key: "{{ ec2_instance_type | regex_replace('\\W', '_') }}"
