(function(){jQuery.fn.compare=function(d){try{d=d.jquery?d[0]:d}catch(q){return null}if(window.HTMLElement){var f=HTMLElement.prototype.toString.call(d);if("[xpconnect wrapped native prototype]"==f||"[object XULElement]"==f||"[object Window]"===f)return null}if(this[0].compareDocumentPosition)return this[0].compareDocumentPosition(d);if(this[0]==document&&d!=document)return 8;var f=(this[0]!==d&&this[0].contains(d)&&16)+(this[0]!=d&&d.contains(this[0])&&8),g=document.documentElement;this[0].sourceIndex&&
(f+=this[0].sourceIndex<d.sourceIndex&&4,f+=this[0].sourceIndex>d.sourceIndex&&2,f+=(this[0].ownerDocument!==d.ownerDocument||this[0]!=g&&0>=this[0].sourceIndex||d!=g&&0>=d.sourceIndex)&&1);return f}})(jQuery);
(function(d){d.fn.range=function(){return d.Range(this[0])};var q=function(a){return a.replace(/([a-z])([a-z]+)/gi,function(a,c,d){return c+d.toLowerCase()}).replace(/_/g,"")},f={};d.Range=function(a){if(this.constructor!==d.Range)return new d.Range(a);a&&a.jquery&&(a=a[0]);!a||a.nodeType?(this.win=a?a.ownerDocument.defaultView||a.ownerDocument.parentWindow:window,this.range=this.win.document.createRange?this.win.document.createRange():this.win.document.body.createTextRange(),a&&this.select(a)):null!=
a.clientX||null!=a.pageX||null!=a.left?this.moveToPoint(a):a.originalEvent&&a.originalEvent.touches&&a.originalEvent.touches.length?this.moveToPoint(a.originalEvent.touches[0]):a.originalEvent&&a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length?this.moveToPoint(a.originalEvent.changedTouches[0]):this.range=a};d.Range.current=function(a){var a=a?a.ownerDocument.defaultView||a.ownerDocument.parentWindow:window,b;return a.getSelection?(b=a.getSelection(),new d.Range(b.rangeCount?b.getRangeAt(0):
a.document.createRange())):new d.Range(a.document.selection.createRange())};d.extend(d.Range.prototype,{moveToPoint:function(a){var b=a.clientX,c=a.clientY;b||(c=r(),b=(a.pageX||a.left||0)-c.left,c=(a.pageY||a.top||0)-c.top);if(f.moveToPoint)return this.range=d.Range().range,this.range.moveToPoint(b,c),this;for(var e=document.elementFromPoint(b,c),s=0;s<e.childNodes.length;s++){var h=e.childNodes[s];if(3===h.nodeType||4===h.nodeType)for(var h=d.Range(h),g=h.toString().length,l=1;l<g+1;l++){var j=
h.end(l).rect();if(j.left<=b&&j.left+j.width>=b&&j.top<=c&&j.top+j.height>=c)return h.start(l-1),this.range=h.range,this}}var k;i(e.childNodes,function(b){b=d.Range(b);if(b.rect().top>a.clientY)return!1;k=b});k?(k.start(k.toString().length),this.range=k.range):this.range=d.Range(e).range},window:function(){return this.win||window},overlaps:function(a){a.nodeType&&(a=d.Range(a).select(a));var b=this.compare("START_TO_START",a),c=this.compare("END_TO_END",a);return 0>=b&&0<=c||0<=b&&0>=this.compare("START_TO_END",
a)||0<=this.compare("END_TO_START",a)&&0>=c?!0:!1},collapse:function(a){this.range.collapse(void 0===a?!0:a);return this},toString:function(){return"string"==typeof this.range.text?this.range.text:this.range.toString()},start:function(a){if(void 0===a){if(this.range.startContainer)return{container:this.range.startContainer,offset:this.range.startOffset};var b=this.clone().collapse().parent(),a=d.Range(b).select(b).collapse();a.move("END_TO_START",this);return{container:b,offset:a.toString().length}}this.range.setStart?
"number"==typeof a?this.range.setStart(this.range.startContainer,a):"string"==typeof a?(b=u(this.range.startContainer,this.range.startOffset,parseInt(a,10)),this.range.setStart(b.node,b.offset)):this.range.setStart(a.container,a.offset):"string"==typeof a?this.range.moveStart("character",parseInt(a,10)):(b=this.start().container,"number"!=typeof a&&(b=a.container,a=a.offset),b=d.Range(b).collapse(),b.range.move(a),this.move("START_TO_START",b));return this},end:function(a){if(void 0===a){if(this.range.startContainer)return{container:this.range.endContainer,
offset:this.range.endOffset};var b=this.clone().collapse(!1).parent(),a=d.Range(b).select(b).collapse();a.move("END_TO_END",this);return{container:b,offset:a.toString().length}}this.range.setEnd?"number"==typeof a?this.range.setEnd(this.range.endContainer,a):"string"==typeof a?(b=u(this.range.endContainer,this.range.endOffset,parseInt(a,10)),this.range.setEnd(b.node,b.offset)):this.range.setEnd(a.container,a.offset):"string"==typeof a?this.range.moveEnd("character",parseInt(a,10)):(b=this.end().container,
"number"!=typeof a&&(b=a.container,a=a.offset),b=d.Range(b).collapse(),b.range.move(a),this.move("END_TO_START",b));return this},parent:function(){if(this.range.commonAncestorContainer)return this.range.commonAncestorContainer;var a=this.range.parentElement(),b=this.range;i(a.childNodes,function(c){if(d.Range(c).range.inRange(b))return a=c,!1});return a},rect:function(a){var b=this.range.getBoundingClientRect();!b.height&&!b.width&&(b=this.range.getClientRects()[0]);"page"===a&&(a=r(),b=d.extend({},
b),b.top+=a.top,b.left+=a.left);return b},rects:function(a){for(var b=d.map(d.makeArray(this.range.getClientRects()).sort(function(a,b){return b.width*b.height-a.width*a.height}),function(a){return d.extend({},a)}),c=0,e;c<b.length;){var f=b[c],g=!1;for(e=c+1;e<b.length;)if(m(f,{clientX:b[e].left,clientY:b[e].top})&&m(f,{clientX:b[e].left+b[e].width,clientY:b[e].top})&&m(f,{clientX:b[e].left,clientY:b[e].top+b[e].height})&&m(f,{clientX:b[e].left+b[e].width,clientY:b[e].top+b[e].height}))if(b[e].width){g=
b[e];break}else b.splice(e,1);else e++;g?b.splice(c,1):c++}if("page"==a){var i=r();return d.each(b,function(a,b){b.top+=i.top;b.left+=i.left})}return b}});var g=d.Range.prototype,n=d.Range().range;g.compare=n.compareBoundaryPoints?function(a,b){return this.range.compareBoundaryPoints(this.window().Range[a.replace(/^([a-z]+)_TO_([a-z]+)/i,function(a,b,d){return d+"_TO_"+b})],b.range)}:function(a,b){return this.range.compareEndPoints(q(a),b.range)};g.move=n.setStart?function(a,b){var c=b.range;switch(a){case "START_TO_END":this.range.setStart(c.endContainer,
c.endOffset);break;case "START_TO_START":this.range.setStart(c.startContainer,c.startOffset);break;case "END_TO_END":this.range.setEnd(c.endContainer,c.endOffset);break;case "END_TO_START":this.range.setEnd(c.startContainer,c.startOffset)}return this}:function(a,b){this.range.setEndPoint(q(a),b.range);return this};var w=n.cloneRange?"cloneRange":"duplicate";g.clone=function(){return d.Range(this.range[w]())};g.select=n.selectNodeContents?function(a){a?this.range.selectNodeContents(a):(a=this.window().getSelection(),
a.removeAllRanges(),a.addRange(this.range));return this}:function(a){if(a)if(3===a.nodeType){var b=a.parentNode,c=0,d;i(b.childNodes,function(b){if(b===a)return d=c+b.nodeValue.length,!1;c+=b.nodeValue.length});this.range.moveToElementText(b);this.range.moveEnd("character",d-this.range.text.length);this.range.moveStart("character",c)}else this.range.moveToElementText(a);else this.range.select();return this};var i=function(a,b){for(var c,d=0;a[d];d++)if(c=a[d],3===c.nodeType||4===c.nodeType){if(!1===
b(c))return!1}else if(8!==c.nodeType&&!1===i(c.childNodes,b))return!1},p=function(a){return 3===a.nodeType||4===a.nodeType},g=function(a,b){return function(c,d){if(c[a]&&!d)return p(c[a])?c[a]:arguments.callee(c[a]);if(c[b])return p(c[b])?c[b]:arguments.callee(c[b]);if(c.parentNode)return arguments.callee(c.parentNode,!0)}},v=g("firstChild","nextSibling"),x=g("lastChild","previousSibling"),u=function(a,b,c){return p(a)?t(a,b+c):a.childNodes[b]?t(a.childNodes[b],c):t(a.lastChild,c,!0)},t=function(a,
b){var c=0>b?x:v,b=Math.abs(b);for(p(a)||(a=c(a));a&&b>=a.nodeValue.length;)hasMany=b-a.nodeValue.length,a=c(a);return{node:a,offset:c===v?b:a.nodeValue.length-b}},m=function(a,b){return a.left<=b.clientX&&a.left+a.width>=b.clientX&&a.top<=b.clientY&&a.top+a.height>=b.clientY},r=function(a){a=a||window;doc=a.document.documentElement;body=a.document.body;return{left:(doc&&doc.scrollLeft||body&&body.scrollLeft||0)+(doc.clientLeft||0),top:(doc&&doc.scrollTop||body&&body.scrollTop||0)+(doc.clientTop||
0)}};f.moveToPoint=!!d.Range().range.moveToPoint})(jQuery);