#!/bin/sh
#
# helper script to copy provisioning scripts to the Arthur machine
#

HOST=108.60.110.146
PORT=4243
USER=eng

rsync -rv -e "ssh -p $PORT" . ${USER}@${HOST}:~/ansible \
  --exclude "*.sw?" \
  --exclude .envrc \
  --exclude .vagrant/ \
  --exclude .cache/
