- hosts: tag_Service_abook
  sudo: yes
  roles:
    - { role: kifi.abook }
- hosts: tag_Service_cortex
  sudo: yes
  roles:
    - { role: kifi.cortex }
- hosts: tag_Service_eliza
  sudo: yes
  roles:
    - { role: kifi.eliza }
- hosts: tag_Service_graph
  sudo: yes
  roles:
    - { role: kifi.graph }
- hosts: tag_Service_heimdal
  sudo: yes
  roles:
    - { role: kifi.heimdal }
- hosts: tag_Service_rover
  sudo: yes
  roles:
    - { role: kifi.rover }
- hosts: tag_Service_search
  sudo: yes
  roles:
    - { role: kifi.search }
- hosts: tag_Service_shoebox
  sudo: yes
  roles:
    - { role: kifi.shoebox }
