- hosts: tag_Service_abook
  become: yes
  roles:
    - { role: kifi.abook }
- hosts: tag_Service_cortex
  become: yes
  roles:
    - { role: kifi.cortex }
- hosts: tag_Service_eliza
  become: yes
  roles:
    - { role: kifi.eliza }
- hosts: tag_Service_graph
  become: yes
  roles:
    - { role: kifi.graph }
- hosts: tag_Service_heimdal
  become: yes
  roles:
    - { role: kifi.heimdal }
- hosts: tag_Service_rover
  become: yes
  roles:
    - { role: kifi.rover }
- hosts: tag_Service_search
  become: yes
  roles:
    - { role: kifi.search }
- hosts: tag_Service_shoebox
  become: yes
  roles:
    - { role: kifi.shoebox }
