---
- hosts: ec2
  sudo: yes
  vars_files:
    - vars/ec2.yml
  pre_tasks:
    - name: create etc/init.d/kifi-register-host
      template:
        src: templates/etc/init.d/kifi-register-host.j2
        dest: /etc/init.d/kifi-register-host
        owner: root
        group: root
        mode: 0774
    - name: enable kifi-register-host service
      command: "update-rc.d kifi-register-host start 90 3 4 5 ."
      changed_when: False
    - command: /etc/init.d/kifi-register-host
      changed_when: False
      register: kifi_hostname
    - set_fact:
        ansible_fqdn: "{{ kifi_hostname.stdout_lines.0 }}"

- hosts: tag_Service_abook
  sudo: yes
  roles:
    - { role: kifi.abook }
- hosts: tag_Service_cortex
  sudo: yes
  roles:
    - { role: kifi.cortex }
- hosts: tag_Service_curator
  sudo: yes
  roles:
    - { role: kifi.curator }
- hosts: tag_Service_eliza
  sudo: yes
  roles:
    - { role: kifi.eliza }
- hosts: tag_Service_graph
  sudo: yes
  roles:
    - { role: kifi.graph }
- hosts: tag_Service_heimdal
  sudo: yes
  roles:
    - { role: kifi.heimdal }
- hosts: tag_Service_rover
  sudo: yes
  roles:
    - { role: kifi.rover }
- hosts: tag_Service_search
  sudo: yes
  roles:
    - { role: kifi.search }
- hosts: tag_Service_shoebox
  sudo: yes
  roles:
    - { role: kifi.shoebox }
