# run this playbook to update existing remote EC2 instances
---
- hosts: ec2
  sudo: yes
  vars_files:
    - vars/ec2.yml
  tasks:
    # remove old init.d script
    - name: remove init.d/kifi-register-host service
      file: state=absent path=/etc/init.d/kifi-register-host

    - name: disable kifi-register-host service
      command: "update-rc.d kifi-register-host remove"
      changed_when: False

    # remove old init service
    - name: remove init/kifi-register-host service
      file: state=absent path=/etc/init/kifi-register-host

    # remove old scripts
    - name: remove /opt/ec2-tags script
      file: state=absent path=/opt/ec2-tags

    - name: remove /opt/kifi-register-host script
      file: state=absent path=/opt/kifi-register-host

- include: kifi-node-setup.yml

- include: ec2-service.yml
