---
- hosts: ec2
  sudo: yes
  vars_files:
    - vars/ec2.yml
  pre_tasks:
    # remove old init.d script
    - name: remove init.d/kifi-register-host service
      file: state=absent path=/etc/init.d/kifi-register-host
    - name: disable kifi-register-host service
      command: "update-rc.d kifi-register-host remove"
      changed_when: False

    # add kifi-register-host as upstart
    - name: add ec2-tag script
      template:
        src: templates/opt/ec2-tags.j2
        dest: /opt/ec2-tags
        owner: root
        group: root
        mode: 751
    - name: add /opt/kifi-register-host script
      template:
        src: templates/opt/kifi-register-host.j2
        dest: /opt/kifi-register-host
        owner: root
        group: root
        mode: 0750
    - name: add /etc/init/kifi-register-host.conf
      template:
        src: templates/etc/init/kifi-register-host.conf.j2
        dest: /etc/init/kifi-register-host.conf
        owner: root
        group: root
        mode: 0750
    - command: /opt/kifi-register-host
      changed_when: False
    - command: /opt/ec2-tags Name
      changed_when: False
      register: kifi_hostname
    - set_fact:
        ansible_fqdn: "{{ kifi_hostname.stdout_lines.0 }}"

- hosts: tag_Service_abook
  sudo: yes
  roles:
    - { role: kifi.abook }
- hosts: tag_Service_cortex
  sudo: yes
  roles:
    - { role: kifi.cortex }
- hosts: tag_Service_curator
  sudo: yes
  roles:
    - { role: kifi.curator }
- hosts: tag_Service_eliza
  sudo: yes
  roles:
    - { role: kifi.eliza }
- hosts: tag_Service_graph
  sudo: yes
  roles:
    - { role: kifi.graph }
- hosts: tag_Service_heimdal
  sudo: yes
  roles:
    - { role: kifi.heimdal }
- hosts: tag_Service_rover
  sudo: yes
  roles:
    - { role: kifi.rover }
- hosts: tag_Service_search
  sudo: yes
  roles:
    - { role: kifi.search }
- hosts: tag_Service_shoebox
  sudo: yes
  roles:
    - { role: kifi.shoebox }
