---
- hosts: all
  sudo: yes

  vars:
    hostname: "{{ hostname_prefix|default('') }}{{ inventory_hostname }}"

  # dependent tasks may depend on the hostname
  pre_tasks:
    - name: set hostname
      hostname: name="{{ hostname }}"
    - name: add {{ hostname }} to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: 127.0.0.1 {{ hostname }}
    - set_fact:
        ansible_fqdn: "{{ hostname }}"

- hosts: shoebox
  sudo: yes
  roles:
  - { role: kifi.shoebox }
